//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DistantVacantGovUz.language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DistantVacantGovUz.language.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &lt;{0}&gt; must have some value
        ///.
        /// </summary>
        internal static string editPortalVacCheckVacField {
            get {
                return ResourceManager.GetString("editPortalVacCheckVacField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exported {0} of {1}.
        ///{2}%.
        /// </summary>
        internal static string exportStatus {
            get {
                return ResourceManager.GetString("exportStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit local vacancy #.
        /// </summary>
        internal static string frmEditLocalVacancyCaption {
            get {
                return ResourceManager.GetString("frmEditLocalVacancyCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portal vacancy edit form - Vacancy #.
        /// </summary>
        internal static string frmEditPortalVacancyCaption {
            get {
                return ResourceManager.GetString("frmEditPortalVacancyCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import vacancies.
        /// </summary>
        internal static string frmImportPortalVacsCaption {
            get {
                return ResourceManager.GetString("frmImportPortalVacsCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        internal static string frmLoadingCaption {
            get {
                return ResourceManager.GetString("frmLoadingCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exiting....
        /// </summary>
        internal static string frmLocalDocExitingCaption {
            get {
                return ResourceManager.GetString("frmLocalDocExitingCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document have unsaved changes. Save changes before exit?.
        /// </summary>
        internal static string frmLocalDocSaveBeforeExit {
            get {
                return ResourceManager.GetString("frmLocalDocSaveBeforeExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local vacancies.
        /// </summary>
        internal static string frmLocalDocumentCaption {
            get {
                return ResourceManager.GetString("frmLocalDocumentCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Untitled document .
        /// </summary>
        internal static string frmMainNewDocumentTitle {
            get {
                return ResourceManager.GetString("frmMainNewDocumentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launcher version: .
        /// </summary>
        internal static string lblAppLauncherVersion {
            get {
                return ResourceManager.GetString("lblAppLauncherVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application version: .
        /// </summary>
        internal static string lblAppVersion {
            get {
                return ResourceManager.GetString("lblAppVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author: .
        /// </summary>
        internal static string lblAuthor {
            get {
                return ResourceManager.GetString("lblAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distant Vacant.Gov.Uz.
        /// </summary>
        internal static string lblProgramName {
            get {
                return ResourceManager.GetString("lblProgramName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vacancies document (*.vacx)|*.vacx|Vacancies document (Old version, *.vac)|*.vac.
        /// </summary>
        internal static string localDocSaveAsFilter {
            get {
                return ResourceManager.GetString("localDocSaveAsFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected: .
        /// </summary>
        internal static string localDocSelectedItems {
            get {
                return ResourceManager.GetString("localDocSelectedItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login failed!
        ///.
        /// </summary>
        internal static string loginFailed {
            get {
                return ResourceManager.GetString("loginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, fill all fields.
        /// </summary>
        internal static string loginFillAllFields {
            get {
                return ResourceManager.GetString("loginFillAllFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About program....
        /// </summary>
        internal static string mnuAboutProgram {
            get {
                return ResourceManager.GetString("mnuAboutProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string mnuHelp {
            get {
                return ResourceManager.GetString("mnuHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to work?.
        /// </summary>
        internal static string mnuHowToWork {
            get {
                return ResourceManager.GetString("mnuHowToWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding local vacancy.
        /// </summary>
        internal static string MsgCaptionAddVacancy {
            get {
                return ResourceManager.GetString("MsgCaptionAddVacancy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening portal vacancy....
        /// </summary>
        internal static string MsgEditPortalVacOpenCaption {
            get {
                return ResourceManager.GetString("MsgEditPortalVacOpenCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot open selected vacancy. 
        ///Error occured..
        /// </summary>
        internal static string MsgEditPortalVacOpenError {
            get {
                return ResourceManager.GetString("MsgEditPortalVacOpenError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving portal vacancy....
        /// </summary>
        internal static string MsgEditPortalVacSaveCaption {
            get {
                return ResourceManager.GetString("MsgEditPortalVacSaveCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vacancy was not saved. 
        ///Error occured..
        /// </summary>
        internal static string MsgEditPortalVacSaveError {
            get {
                return ResourceManager.GetString("MsgEditPortalVacSaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving local vacancy....
        /// </summary>
        internal static string MsgEditSavingLocalVacancyCaption {
            get {
                return ResourceManager.GetString("MsgEditSavingLocalVacancyCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import finished. Imported {0} from {1}.
        /// </summary>
        internal static string MsgImportPortalVacsFinished {
            get {
                return ResourceManager.GetString("MsgImportPortalVacsFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importing vacancies....
        /// </summary>
        internal static string MsgImportVacsCaption {
            get {
                return ResourceManager.GetString("MsgImportVacsCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete selected rows?.
        /// </summary>
        internal static string MsgLocalDocDeletingRows {
            get {
                return ResourceManager.GetString("MsgLocalDocDeletingRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting rows....
        /// </summary>
        internal static string MsgLocalDocDeletingRowsCaption {
            get {
                return ResourceManager.GetString("MsgLocalDocDeletingRowsCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving document....
        /// </summary>
        internal static string MsgLocalVacSaveCaption {
            get {
                return ResourceManager.GetString("MsgLocalVacSaveCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured while document saving.
        /// </summary>
        internal static string MsgLocVacSaveError {
            get {
                return ResourceManager.GetString("MsgLocVacSaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some fields not filled.
        ///Continue save?.
        /// </summary>
        internal static string MsgNotAllFieldsFilled {
            get {
                return ResourceManager.GetString("MsgNotAllFieldsFilled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document is already opened.
        /// </summary>
        internal static string MsgOpenVacancyDocumentAlreadyOpened {
            get {
                return ResourceManager.GetString("MsgOpenVacancyDocumentAlreadyOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening document....
        /// </summary>
        internal static string MsgOpenVacancyDocumentCaption {
            get {
                return ResourceManager.GetString("MsgOpenVacancyDocumentCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured while loading document.
        ///Reason: .
        /// </summary>
        internal static string MsgOpenVacancyDocumentError {
            get {
                return ResourceManager.GetString("MsgOpenVacancyDocumentError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporting vacancies....
        /// </summary>
        internal static string MsgPortalVacExportCaption {
            get {
                return ResourceManager.GetString("MsgPortalVacExportCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exported vacancies save error..
        /// </summary>
        internal static string MsgPortalVacExportSaveError {
            get {
                return ResourceManager.GetString("MsgPortalVacExportSaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vacancies successfully exported and saved..
        /// </summary>
        internal static string MsgPortalVacExportSuccess {
            get {
                return ResourceManager.GetString("MsgPortalVacExportSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changing status....
        /// </summary>
        internal static string MsgPortalVacStatusChangeCaption {
            get {
                return ResourceManager.GetString("MsgPortalVacStatusChangeCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %d of %d vacancies status changed..
        /// </summary>
        internal static string MsgPortalVacStatusChanged {
            get {
                return ResourceManager.GetString("MsgPortalVacStatusChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select document to import....
        /// </summary>
        internal static string openVacancyDocImportTitle {
            get {
                return ResourceManager.GetString("openVacancyDocImportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vacancies document file (*.vac, *.vacx)|*.vac;*.vacx.
        /// </summary>
        internal static string openVacancyDocumentFilter {
            get {
                return ResourceManager.GetString("openVacancyDocumentFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose vacancies document file.
        /// </summary>
        internal static string openVacancyDocumentTitle {
            get {
                return ResourceManager.GetString("openVacancyDocumentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imported.
        /// </summary>
        internal static string portalImportVacStatusImported {
            get {
                return ResourceManager.GetString("portalImportVacStatusImported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import error.
        /// </summary>
        internal static string portalImportVacStatusImportError {
            get {
                return ResourceManager.GetString("portalImportVacStatusImportError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not imported.
        /// </summary>
        internal static string portalImportVacStatusNotImported {
            get {
                return ResourceManager.GetString("portalImportVacStatusNotImported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skipped.
        /// </summary>
        internal static string portalImportVacStatusSkipped {
            get {
                return ResourceManager.GetString("portalImportVacStatusSkipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vacancy have uncompleted fields.
        /// </summary>
        internal static string portalImportVacStatusUncompleted {
            get {
                return ResourceManager.GetString("portalImportVacStatusUncompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporting .
        /// </summary>
        internal static string portalVacExporting {
            get {
                return ResourceManager.GetString("portalVacExporting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vacancies document (*.vacx)|*.vacx.
        /// </summary>
        internal static string portalVacExportSaveFilter {
            get {
                return ResourceManager.GetString("portalVacExportSaveFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sherzod Mutalov.
        /// </summary>
        internal static string ProgramAuthor {
            get {
                return ResourceManager.GetString("ProgramAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot initialize proxy: .
        /// </summary>
        internal static string stateCannotInitializeProxy {
            get {
                return ResourceManager.GetString("stateCannotInitializeProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download error: .
        /// </summary>
        internal static string stateDownloadError {
            get {
                return ResourceManager.GetString("stateDownloadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading update file: .
        /// </summary>
        internal static string stateDownloadingUpdateFile {
            get {
                return ResourceManager.GetString("stateDownloadingUpdateFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading update version file: .
        /// </summary>
        internal static string stateDownloadingUpdateVersionFile {
            get {
                return ResourceManager.GetString("stateDownloadingUpdateVersionFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR: .
        /// </summary>
        internal static string stateError {
            get {
                return ResourceManager.GetString("stateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR: Launcher not found.
        /// </summary>
        internal static string stateErrorLauncherNotFound {
            get {
                return ResourceManager.GetString("stateErrorLauncherNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File downloaded.
        /// </summary>
        internal static string stateFileDownloaded {
            get {
                return ResourceManager.GetString("stateFileDownloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launcher current version: .
        /// </summary>
        internal static string stateLauncherCurrentVersion {
            get {
                return ResourceManager.GetString("stateLauncherCurrentVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launcher successfully updated!.
        /// </summary>
        internal static string stateLauncherSuccessfullyUpdated {
            get {
                return ResourceManager.GetString("stateLauncherSuccessfullyUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launcher update start....
        /// </summary>
        internal static string stateLauncherUpdateStart {
            get {
                return ResourceManager.GetString("stateLauncherUpdateStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launcher version on server: .
        /// </summary>
        internal static string stateLauncherVersionOnServer {
            get {
                return ResourceManager.GetString("stateLauncherVersionOnServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New version is available.
        /// </summary>
        internal static string stateNewVersionIsAvailable {
            get {
                return ResourceManager.GetString("stateNewVersionIsAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unpack error.
        /// </summary>
        internal static string stateUnpackError {
            get {
                return ResourceManager.GetString("stateUnpackError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using proxy-server.
        /// </summary>
        internal static string stateUsingProxyServer {
            get {
                return ResourceManager.GetString("stateUsingProxyServer", resourceCulture);
            }
        }
    }
}
