//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DistantVacantGovUz.language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DistantVacantGovUz.language.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launcher version: .
        /// </summary>
        internal static string lblAppLauncherVersion {
            get {
                return ResourceManager.GetString("lblAppLauncherVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application version: .
        /// </summary>
        internal static string lblAppVersion {
            get {
                return ResourceManager.GetString("lblAppVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author: .
        /// </summary>
        internal static string lblAuthor {
            get {
                return ResourceManager.GetString("lblAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distant Vacant.Gov.Uz.
        /// </summary>
        internal static string lblProgramName {
            get {
                return ResourceManager.GetString("lblProgramName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About program....
        /// </summary>
        internal static string mnuAboutProgram {
            get {
                return ResourceManager.GetString("mnuAboutProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string mnuHelp {
            get {
                return ResourceManager.GetString("mnuHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to work?.
        /// </summary>
        internal static string mnuHowToWork {
            get {
                return ResourceManager.GetString("mnuHowToWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sherzod Mutalov.
        /// </summary>
        internal static string ProgramAuthor {
            get {
                return ResourceManager.GetString("ProgramAuthor", resourceCulture);
            }
        }
    }
}
