//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DistantVacantGovUzLauncher.language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    var temp = new global::System.Resources.ResourceManager("DistantVacantGovUzLauncher.language.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string btnCancel_CloseText {
            get {
                return ResourceManager.GetString("btnCancel_CloseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        internal static string btnCancel_ContinueText {
            get {
                return ResourceManager.GetString("btnCancel_ContinueText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot launch application!
        ///{0}
        ///{1}.
        /// </summary>
        internal static string MsgLaunchAppError {
            get {
                return ResourceManager.GetString("MsgLaunchAppError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch error.
        /// </summary>
        internal static string MsgLaunchAppErrorCaption {
            get {
                return ResourceManager.GetString("MsgLaunchAppErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application current version: .
        /// </summary>
        internal static string stateApplicationCurrentVersion {
            get {
                return ResourceManager.GetString("stateApplicationCurrentVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application version on server: .
        /// </summary>
        internal static string stateApplicationVersionOnServer {
            get {
                return ResourceManager.GetString("stateApplicationVersionOnServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting version info: Cannot read file..
        /// </summary>
        internal static string stateGettingVersionInfoCannotReadFile {
            get {
                return ResourceManager.GetString("stateGettingVersionInfoCannotReadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting version info: Checking version....
        /// </summary>
        internal static string stateGettingVersionInfoCheckingVersion {
            get {
                return ResourceManager.GetString("stateGettingVersionInfoCheckingVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting version info: Download failed....
        /// </summary>
        internal static string stateGettingVersionInfoDownloadFailed {
            get {
                return ResourceManager.GetString("stateGettingVersionInfoDownloadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting version info: Downloading file....
        /// </summary>
        internal static string stateGettingVersionInfoDownloadingFile {
            get {
                return ResourceManager.GetString("stateGettingVersionInfoDownloadingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting version info: File downloaded....
        /// </summary>
        internal static string stateGettingVersionInfoFileDownloaded {
            get {
                return ResourceManager.GetString("stateGettingVersionInfoFileDownloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy server: .
        /// </summary>
        internal static string stateProxyServer {
            get {
                return ResourceManager.GetString("stateProxyServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no updates..
        /// </summary>
        internal static string stateThereAreNoUpdates {
            get {
                return ResourceManager.GetString("stateThereAreNoUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is new application version: Applying updates....
        /// </summary>
        internal static string stateThereIsNewApplicationVersionApplyingUpdates {
            get {
                return ResourceManager.GetString("stateThereIsNewApplicationVersionApplyingUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is new application version: Download failed....
        /// </summary>
        internal static string stateThereIsNewApplicationVersionDownloadFailed {
            get {
                return ResourceManager.GetString("stateThereIsNewApplicationVersionDownloadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is new application version: Downloading....
        /// </summary>
        internal static string stateThereIsNewApplicationVersionDownloading {
            get {
                return ResourceManager.GetString("stateThereIsNewApplicationVersionDownloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is new application version: Unpack error..
        /// </summary>
        internal static string stateThereIsNewApplicationVersionUnpackError {
            get {
                return ResourceManager.GetString("stateThereIsNewApplicationVersionUnpackError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update server: .
        /// </summary>
        internal static string stateUpdateServer {
            get {
                return ResourceManager.GetString("stateUpdateServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updates successfully applyed..
        /// </summary>
        internal static string stateUpdatesSuccessfullyApplyed {
            get {
                return ResourceManager.GetString("stateUpdatesSuccessfullyApplyed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot retreive application current version..
        /// </summary>
        internal static string statusCannotRetreiveApplicationCurrentVersion {
            get {
                return ResourceManager.GetString("statusCannotRetreiveApplicationCurrentVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured..
        /// </summary>
        internal static string statusErrorOccured {
            get {
                return ResourceManager.GetString("statusErrorOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished..
        /// </summary>
        internal static string statusFinished {
            get {
                return ResourceManager.GetString("statusFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation canceled..
        /// </summary>
        internal static string statusOperationCanceled {
            get {
                return ResourceManager.GetString("statusOperationCanceled", resourceCulture);
            }
        }
    }
}
